# FORCE BUILD
language: haskell

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libnetcdf-dev
 - cabal install --only-dependencies --enable-tests
 - cabal install c2hs

install: true
