addons:
  apt:
    packages:
      - libgmp-dev

before_install:
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install libnetcdf-dev libgsl0-dev liblapack-dev

install:
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=~/.local/bin:$PATH
  - stack --version

script:
 - stack setup
 - stack update
 - stack build
 - stack test

cache:
  directories:
    - $HOME/.stack
