env:
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.4
 - GHCVER=7.10.1

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install libnetcdf-dev libgsl0-dev liblapack-dev
 - travis_retry sudo apt-get install cabal-install-1.22 ghc-$GHCVER-prof ghc-$GHCVER-dyn happy
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.22/bin:$PATH

install:
 - cabal update
 - cabal install alex happy
 - cabal install --only-dependencies --enable-tests --reorder-goals
 - cabal install c2hs

script:
 - cabal install && cabal configure --enable-tests && cabal build && cabal test
